Refactor kernel repository initialization in workflow
Updated the workflow to initialize the kernel repository and synchronize the codebase.

diff --git a/.github/workflows/plz_small.yml b/.github/workflows/plz_small.yml
--- a/.github/workflows/plz_small.yml
+++ b/.github/workflows/plz_small.yml
@@ -101,20 +101,21 @@ jobs:
           wait
 
           # ΕΚΤΕΛΕΣΗ CLONE ΣΤΟ ΠΡΟΣΚΗΝΙΟ (Foreground) για άμεση καταγραφή σφαλμάτων
-          echo "Cloning source repository..."
+          #echo "Cloning source repository..."
           #git clone --depth=1 https://github.com/Evolution-X-Devices/kernel_xiaomi_garnet -b bka kernel_workspace/common || { echo "❌ ERROR: Git clone failed!"; exit 1; }
           #git clone --depth=1 "https://github.com/UserXP-web/Zen-ItsuKernel-Garnet" -b Zen-Itsu-Garnet kernel_workspace/common || { echo "❌ ERROR: Git clone failed!"; exit 1; }
-          git clone --depth=1 https://github.com/crdroidandroid/android_xiaomi_kernel_garnet -b 16.0 kernel_workspace/common || { echo "❌ ERROR: Git clone failed!"; exit 1; }
-          #echo "🌐 Initialize kernel repository..."
-          ##mkdir -p android && cd android          
-          #MANIFEST_URL="https://github.com/UserXP-web/kernel_build" # ${{ env.manifest_url }}
-          #MANIFEST_BRANCH="main" # ${{ env.manifest_branch }}
-          #MANIFEST_XML="manifest/zylhdrXP.xml" # manifest/${{ inputs.MANIFEST_selection }}.xml
-          #echo "~ $MANIFEST_URL ^^^ $MANIFEST_BRANCH --- $MANIFEST_XML"        
-          #repo init --depth=1 -u $MANIFEST_URL -b $MANIFEST_BRANCH -m $MANIFEST_XML
-          #echo "🔄 Synchronize the codebase (using $(nproc --all) threads)..."
-          #repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle --force-sync
-          #echo "✅ Kernel source code cloning complete"
+          #git clone --depth=1 https://github.com/crdroidandroid/android_xiaomi_kernel_garnet -b 16.0 kernel_workspace/common || { echo "❌ ERROR: Git clone failed!"; exit 1; }
+          echo "🌐 Initialize kernel repository..."
+          #mkdir -p android && cd android
+          mkdir -p kernel_workspace && cd kernel_workspace
+          MANIFEST_URL="https://github.com/UserXP-web/kernel_build" # ${{ env.manifest_url }}
+          MANIFEST_BRANCH="main" # ${{ env.manifest_branch }}
+          MANIFEST_XML="manifest/zylhdrXP.xml" # manifest/${{ inputs.MANIFEST_selection }}.xml
+          echo "~ $MANIFEST_URL ^^^ $MANIFEST_BRANCH --- $MANIFEST_XML"        
+          repo init --depth=1 -u $MANIFEST_URL -b $MANIFEST_BRANCH -m $MANIFEST_XML
+          echo "🔄 Synchronize the codebase (using $(nproc --all) threads)..."
+          repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle --force-sync
+          echo "✅ Kernel source code cloning complete"
 
 
           echo "Removing ABI protection & dirty suffix..."
